from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()

app_settings = Table(
    "app_settings",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("scope", String(32), nullable=False, server_default="global"),
    Column("key", String(120), nullable=False),
    Column("value", JSONB, nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("scope", "key", name="uq_app_settings_scope_key"),
)

clubs = Table(
    "clubs",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("short_name", String(32), nullable=False, unique=True),
    Column("full_name", String(120), nullable=False),
    Column("description", Text, nullable=False, server_default=""),
    Column("website_url", String(255), nullable=False, server_default=""),
    Column("admin_email", String(255), nullable=False, server_default=""),
    Column("logo_url", String(255), nullable=False, server_default=""),
    Column("is_active", Boolean, nullable=False, server_default="true"),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

club_smtp_settings = Table(
    "club_smtp_settings",
    metadata,
    Column("club_id", BigInteger, ForeignKey("clubs.id", ondelete="CASCADE"), primary_key=True),
    Column("host", String(255), nullable=False, server_default=""),
    Column("port", Integer, nullable=False, server_default="587"),
    Column("username", String(255), nullable=False, server_default=""),
    Column("password", String(255), nullable=False, server_default=""),
    Column("from_email", String(255), nullable=False, server_default=""),
    Column("from_name", String(255), nullable=False, server_default=""),
    Column("use_ssl", Boolean, nullable=False, server_default="false"),
    Column("use_tls", Boolean, nullable=False, server_default="true"),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

club_beats = Table(
    "club_beats",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("club_id", BigInteger, ForeignKey("clubs.id", ondelete="CASCADE"), nullable=False),
    Column("beat_name", String(255), nullable=False, server_default=""),
    Column("beat_id", String(64), nullable=False, server_default=""),
    Column("river", String(255), nullable=False, server_default=""),
    Column("position", String(120), nullable=False, server_default=""),
    Column("beat_upstream", String(120), nullable=False, server_default=""),
    Column("beat_downstream", String(120), nullable=False, server_default=""),
    Column("beat_description", Text, nullable=False, server_default=""),
    Column("detailed_description", Text, nullable=False, server_default=""),
    Column("beat_upstream_latitude", String(64), nullable=False, server_default=""),
    Column("beat_upstream_longitude", String(64), nullable=False, server_default=""),
    Column("beat_downstream_latitude", String(64), nullable=False, server_default=""),
    Column("beat_downstream_longitude", String(64), nullable=False, server_default=""),
    Column("parking_locations", JSONB, nullable=False, server_default="[]"),
    UniqueConstraint("club_id", "beat_id", name="uq_club_beats_club_id_beat_id"),
)

members = Table(
    "members",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("club_id", BigInteger, ForeignKey("clubs.id", ondelete="CASCADE"), nullable=False),
    Column("legacy_id", String(64), nullable=False, server_default=""),
    Column("number", String(64), nullable=False, server_default=""),
    Column("members_name", String(255), nullable=False, server_default=""),
    Column("title", String(64), nullable=False, server_default=""),
    Column("first_name", String(120), nullable=False, server_default=""),
    Column("last_name", String(120), nullable=False, server_default=""),
    Column("photo_path", String(512), nullable=False, server_default=""),
    Column("preferred_name", String(120), nullable=False, server_default=""),
    Column("first_names", String(255), nullable=False, server_default=""),
    Column("paused", String(32), nullable=False, server_default=""),
    Column("resigned", String(32), nullable=False, server_default=""),
    Column("member_type", String(120), nullable=False, server_default=""),
    Column("subs_expected", String(64), nullable=False, server_default=""),
    Column("subs_paid", String(64), nullable=False, server_default=""),
    Column("join_fee", String(64), nullable=False, server_default=""),
    Column("paid_up_2026", String(64), nullable=False, server_default=""),
    Column("photo_received", String(64), nullable=False, server_default=""),
    Column("in_whatsapp", String(64), nullable=False, server_default=""),
    Column("in_fb", String(64), nullable=False, server_default=""),
    Column("date_of_birth", Date, nullable=True),
    Column("age", String(32), nullable=False, server_default=""),
    Column("new_member_2026", String(64), nullable=False, server_default=""),
    Column("paid_up_card_sent", String(64), nullable=False, server_default=""),
    Column("cr2023", String(64), nullable=False, server_default=""),
    Column("cr2024", String(64), nullable=False, server_default=""),
    Column("cr2025", String(64), nullable=False, server_default=""),
    Column("details_confirmed_2026", String(64), nullable=False, server_default=""),
    Column("full_address", Text, nullable=False, server_default=""),
    Column("address_street", String(255), nullable=False, server_default=""),
    Column("address_line_2", String(255), nullable=False, server_default=""),
    Column("address_city", String(120), nullable=False, server_default=""),
    Column("county", String(120), nullable=False, server_default=""),
    Column("address_state_region", String(120), nullable=False, server_default=""),
    Column("address_zip_postal", String(64), nullable=False, server_default=""),
    Column("address_country", String(120), nullable=False, server_default=""),
    Column("phone", String(64), nullable=False, server_default=""),
    Column("mobile", String(64), nullable=False, server_default=""),
    Column("email", String(255), nullable=False, server_default=""),
    Column("ea_licence", String(64), nullable=False, server_default=""),
    Column("licence_exp", String(64), nullable=False, server_default=""),
    Column("car_reg", String(64), nullable=False, server_default=""),
    Column("username", String(255), nullable=False, server_default=""),
    Column("password", String(255), nullable=False, server_default=""),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("club_id", "number", name="uq_members_club_number"),
)

newsletter_templates = Table(
    "newsletter_templates",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("club_id", BigInteger, ForeignKey("clubs.id", ondelete="CASCADE"), nullable=False),
    Column("template_key", String(120), nullable=False, server_default=""),
    Column("name", String(255), nullable=False),
    Column("subject", Text, nullable=False),
    Column("body", Text, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("club_id", "template_key", name="uq_newsletter_templates_club_template_key"),
)
