"""add_beat_map_rotations_table

Revision ID: 20260512_0001
Revises: 20260511_0001
Create Date: 2026-05-12 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260512_0001'
down_revision = '20260511_0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beat_map_rotations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('beat_id', sa.BigInteger(), nullable=False),
    sa.Column('rotation_bearing', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['club_beats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beat_map_rotations')
    # ### end Alembic commands ###
